# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Site Config
title:            solstat
tagline:          'Sunday Statistics'
description:      'Just another weekend statistics club.'
url:
baseurl:          /

paginate:         5

# Custom Jekyll Gems
gems:
  - jekyll-sitemap  # For generating a sitemap (for webcrawlers)
  - jekyll/scholar  # For bibtex
  - jekyll-paginate # For blog

# Jekyll Scholar Bibtex Formatting
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  source: ./_data
  bibliography: publications.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bib_details.html
#  details_link:   " Details"

  query: "@*"

  repository: ./pdf

# Exclude from site build
exclude: ["Gemfile", "Gemfile.lock",
    "README.md", "build.sh", "deploy-to-master.sh", "Rakefile"]
